[package]
name = "gol"
version = "0.1.0"
authors = ["tlrobrn <obrien.taylorm@gmail.com>"]

[dependencies]
piston = "0.32.0"
piston2d-graphics = "0.21.1"
pistoncore-glutin_window = "0.36.0"
piston2d-opengl_graphics = "0.43.0"
rand = "0.3"
